version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    networks:
      - app-network
    depends_on:
      main-db:
        condition: service_healthy
      read-db:
        condition: service_healthy
    environment:
      JWT_SECRET: super-secret
      JWT_REFRESH_SECRET: super-sa-vi-uper-ka-secret
      DATABASE_URL: mysql://myuser:mypassword@main-db:3306/myapp
      READ_DATABASE_URL: mysql://myuser:mypassword@read-db:3306/myapp
      PORT: 3333
      CLOUDINARY_API_KEY: 536853457982797
      CLOUDINARY_CLOUD_NAME: ujjwalbhandari
      CLOUDINARY_API_SECRET: y0Wzum7hQDh_Ntz4vuE_3942AGQ
      CLOUDINARY_UPLOAD_PRESET: medi_nepal_uploads
      CLOUDINARY_IMAGE_UPLOAD_LINK: https://api.cloudinary.com/v1_1/ujjwalbhandari
      FRONTEND_URL: http://localhost:4200

  main-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - main-db-data:/var/lib/mysql
      - ./mysql-main.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5

  read-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3307:3306'
    volumes:
      - read-db-data:/var/lib/mysql
      - ./mysql-replica.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  main-db-data:
  read-db-data:
