import { RoomsType } from '@/app/types';

export const rooms = {
  data: [
    {
      id: 'room-1-ASASMabc123',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 1 in Lalitpur',
      description:
        'A spacious 3-bedroom house with modern amenities in Lalitpur.',
      price: 250000,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1500,
      availability_to: new Date('2024-12-31T00:00:00.000Z'),
      availability_from: new Date('2024-10-01T00:00:00.000Z'),
      location: '123 Main St, Lalitpur',
      images: [
        {
          id: '1',
          url: 'https://www.houzlook.com/assets/images/upload/Rooms/Bed%20Rooms/View_01-20200822103638797.jpg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: 'asnans1',
        },
      ],
      average_rating: 4.5,
      categoryId: 'category-1',
      userId: 'user-1',
    },
    {
      id: 'room-2-def456',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 2 in Kathmandu',
      description: 'A cozy 2-bedroom apartment in the heart of Kathmandu.',
      price: 200000,
      bedrooms: 2,
      bathrooms: 1,
      sqft: 1200,
      availability_to: new Date('2024-11-30T00:00:00.000Z'),
      availability_from: new Date('2024-09-15T00:00:00.000Z'),
      location: '456 Second Ave, Kathmandu',
      images: [
        {
          id: 'askask2',
          url: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '2',
        },
      ],
      average_rating: 4.0,
      categoryId: 'category-2',
      userId: 'user-2',
    },
    {
      id: 'room-3-ghi789',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 3 in Bhaktapur',
      description: 'A luxurious 4-bedroom villa in the outskirts of Bhaktapur.',
      price: 400000,
      bedrooms: 4,
      bathrooms: 3,
      sqft: 2000,
      availability_to: new Date('2024-12-15T00:00:00.000Z'),
      availability_from: new Date('2024-09-01T00:00:00.000Z'),
      location: '789 Hill View Rd, Bhaktapur',
      images: [
        {
          id: '3asnkas',
          url: 'https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '3',
        },
      ],
      average_rating: 4.8,
      categoryId: 'category-3',
      userId: 'user-3',
    },
    {
      id: '129128912-12918291-sdksd',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Kathmandu Royal Stars',
      description: 'A cozy 3-bedroom house with great amenities.',
      price: 250000,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1500,
      availability_to: new Date('2024-12-31T00:00:00.000Z'),
      availability_from: new Date('2024-10-01T00:00:00.000Z'),
      location: 'Basantaur Area - Kathmandu',
      images: [
        {
          id: '1aksaksspapspas',
          url: 'https://images.pexels.com/photos/97083/pexels-photo-97083.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '1',
        },
      ],
      average_rating: 4,
      categoryId: '177c5745-b146-44a6-8bb5-578460e84afc',
      userId: 'e336dd4f-c3a5-44ea-b09a-ad1e36189ed2',
    },
    {
      id: 'room-6-pqr678',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 6 in Janakpur',
      description:
        'A charming 4-bedroom house in the cultural hub of Janakpur.',
      price: 300000,
      bedrooms: 4,
      bathrooms: 3,
      sqft: 1800,
      availability_to: new Date('2024-12-20T00:00:00.000Z'),
      availability_from: new Date('2024-10-05T00:00:00.000Z'),
      location: '404 Temple Rd, Janakpur',
      images: [
        {
          id: '6askalsll,',
          url: 'https://www.houzlook.com/assets/images/upload/Rooms/Bed%20Rooms/View_01-20200822103638797.jpg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '6',
        },
      ],
      average_rating: 4.6,
      categoryId: 'category-6',
      userId: 'user-6',
    },
    {
      id: 'room-7-stu901',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 7 in Dharan',
      description:
        'A cozy 1-bedroom studio in a bustling neighborhood of Dharan.',
      price: 150000,
      bedrooms: 1,
      bathrooms: 1,
      sqft: 800,
      availability_to: new Date('2024-10-31T00:00:00.000Z'),
      availability_from: new Date('2024-09-25T00:00:00.000Z'),
      location: '505 Market St, Dharan',
      images: [
        {
          id: '7',
          url: 'https://images.pexels.com/photos/97083/pexels-photo-97083.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '7',
        },
      ],
      average_rating: 4.1,
      categoryId: 'category-7',
      userId: 'user-7',
    },
    {
      id: 'room-8-abc123',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 1 in Lalitpur',
      description:
        'A spacious 3-bedroom house with modern amenities in Lalitpur.',
      price: 250000,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1500,
      availability_to: new Date('2024-12-31T00:00:00.000Z'),
      availability_from: new Date('2024-10-01T00:00:00.000Z'),
      location: '123 Main St, Lalitpur',
      images: [
        {
          id: '1',
          url: 'https://www.houzlook.com/assets/images/upload/Rooms/Bed%20Rooms/View_01-20200822103638797.jpg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '1',
        },
      ],
      average_rating: 4.5,
      categoryId: 'category-1',
      userId: 'user-1',
    },
    {
      id: 'room-9ajsjkajs-def456',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 2 in Kathmandu',
      description: 'A cozy 2-bedroom apartment in the heart of Kathmandu.',
      price: 200000,
      bedrooms: 2,
      bathrooms: 1,
      sqft: 1200,
      availability_to: new Date('2024-11-30T00:00:00.000Z'),
      availability_from: new Date('2024-09-15T00:00:00.000Z'),
      location: '456 Second Ave, Kathmandu',
      images: [
        {
          id: '2',
          url: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '2',
        },
      ],
      average_rating: 4.0,
      categoryId: 'category-2',
      userId: 'user-2',
    },
    {
      id: 'room-10skas-ghi789',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 3 in Bhaktapur',
      description: 'A luxurious 4-bedroom villa in the outskirts of Bhaktapur.',
      price: 400000,
      bedrooms: 4,
      bathrooms: 3,
      sqft: 2000,
      availability_to: new Date('2024-12-15T00:00:00.000Z'),
      availability_from: new Date('2024-09-01T00:00:00.000Z'),
      location: '789 Hill View Rd, Bhaktapur',
      images: [
        {
          id: '3',
          url: 'https://images.pexels.com/photos/237371/pexels-photo-237371.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '3',
        },
      ],
      average_rating: 4.8,
      categoryId: 'category-3',
      userId: 'user-3',
    },
    {
      id: '129128912askasjkas-12918291-sdksd',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Kathmandu Royal Stars',
      description: 'A cozy 3-bedroom house with great amenities.',
      price: 250000,
      bedrooms: 3,
      bathrooms: 2,
      sqft: 1500,
      availability_to: new Date('2024-12-31T00:00:00.000Z'),
      availability_from: new Date('2024-10-01T00:00:00.000Z'),
      location: 'Basantaur Area - Kathmandu',
      images: [
        {
          id: '1aksaksl',
          url: 'https://images.pexels.com/photos/3659683/pexels-photo-3659683.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '1',
        },
      ],
      average_rating: 4,
      categoryId: '177c5745-b146-44a6-8bb5-578460e84afc',
      userId: 'e336dd4f-c3a5-44ea-b09a-ad1e36189ed2',
    },
    {
      id: 'room-6-pasmla;slalsqr678',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 6 in Janakpur',
      description:
        'A charming 4-bedroom house in the cultural hub of Janakpur.',
      price: 300000,
      bedrooms: 4,
      bathrooms: 3,
      sqft: 1800,
      availability_to: new Date('2024-12-20T00:00:00.000Z'),
      availability_from: new Date('2024-10-05T00:00:00.000Z'),
      location: '404 Temple Rd, Janakpur',
      images: [
        {
          id: '6asAKSKAS',
          url: 'https://www.houzlook.com/assets/images/upload/Rooms/Bed%20Rooms/View_01-20200822103638797.jpg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '6',
        },
      ],
      average_rating: 4.6,
      categoryId: 'category-6',
      userId: 'user-6',
    },
    {
      id: 'roomASALKS;LASL-7-stu901',
      created_at: new Date(),
      updated_at: new Date(),
      title: 'Room 7 in Dharan',
      description:
        'A cozy 1-bedroom studio in a bustling neighborhood of Dharan.',
      price: 150000,
      bedrooms: 1,
      bathrooms: 1,
      sqft: 800,
      availability_to: new Date('2024-10-31T00:00:00.000Z'),
      availability_from: new Date('2024-09-25T00:00:00.000Z'),
      location: '505 Market St, Dharan',
      images: [
        {
          id: 'SNDLSNDLKKLSD7',
          url: 'https://images.pexels.com/photos/97083/pexels-photo-97083.jpeg',
          created_at: new Date(),
          updated_at: new Date(),
          listingId: '7',
        },
      ],
      average_rating: 4.1,
      categoryId: 'category-7',
      userId: 'user-7',
    },
  ],
  meta: {
    hasNextPage: false,
    hasPreviousPage: false,
    itemCount: 0,
    pageCount: 0,
  },
} satisfies RoomsType;
